export const types = {
    EMAIL_SENDING:  "EMAIL_SENDING",
    EMAIL_SENT: "EMAIL_SENT",
    EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
    EMAIL_SEND_ERROR: "EMAIL_SEND_ERROR",
    EMAIL_CHANGED: "EMAIL_CHANGED",
    USER_KEY_RECEIVED: "USER_KEY_RECEIVED",
    USER_KEY_TIMER_INIT: "USER_KEY_TIMER_INIT",
    GO_NEXT: "GO_NEXT"
}