# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm ci
    - run: npm run build

    #Setup key
    - run: set -eu
    - run: mkdir "$HOME/.ssh"
    - run: echo "${{ secrets.SSH_KEY }}" > "$HOME/.ssh/key"
    - run: cat "$HOME/.ssh/key"
    - run: chmod 600 "$HOME/.ssh/key"
    #Deploy
    - run: cd ./build && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no -p 22 -c aes256-cbc -oKexAlgorithms=+diffie-hellman-group1-sha1" --archive --compress --delete . root@195.133.46.76:/var/www/sites/snt-romashka24
    
