export const types = {
    KEYCODE_CHANGED: "KEYCODE_CHANGED",
    KEYCODE_SENDING: "KEYCODE_SENDING",
    KEYCODE_SEND_FAILED: "KEYCODE_SEND_FAILED",
    KEYCODE_SENT_SUCCESS: "KEYCODE_SENT_SUCCESS",
    KEYCODE_SENT_ERROR: "KEYCODE_SENT_ERROR",
    GO_BACK: "GO_BACK"
}